### PR TITLE
Update 0416.lang

### PR DESCRIPTION
**Pull request by maisondasilva**
Add line 0 Drives Meet Requirements and RTL Line

Please describe your feature/changes on this pull:

> if this pull request **not** a localization related, please fill and check on this below

Please Screenshot/Capture your WNW11 new feature to demonstrate:

Which your feature we're added on this pull:

- [ ] I had read the [contributing guidelines](CONTRIBUTING.md)
- [ ] I ensured that my code compiles, if applicable
- [ ] I ensured that my feature works properly, if applicable

### CODE REVIEW

**Review by rcmaehl — APPROVED** [review]

**Comment by rcmaehl** [comment]
@DanGM96 @eduardoaddad Any objections?

**Comment by maisondasilva** [comment]
I believe the @eduardoaddad , approved
The Line RTL true or false what function does it serve? @rcmaehl

**Comment by micwoj92** [comment]
true for RTL languages such as Arabic or Hebrew

**Comment by maisondasilva** [comment]
> true for RTL languages such as Arabic or Hebrew

Ah true, I thought it was some system variable with that name. Thanks

**Pull request merged**
