### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by konmaz**
Fixed typo in Greek Language file

### CODE REVIEW

**Comment by micwoj92** [comment]
@Mant08 do you approve?

**Comment by micwoj92** [comment]
@konmaz Please add yourself (github nickname) to translator and bump metadata version to 2.3.0.4. Then it is ready to merge, thanks!

**Comment by Mant08** [comment]
He has my approval

**Comment by micwoj92** [comment]
Ok, merging then and will update metadata manually.

**Pull request merged**
