### PR TITLE
ExtractFiles refactor :

### PR DESCRIPTION
**Pull request by PierreGrillet**
- Create CopyLangFiles
- CopyLangFiles scan Langs folder to get a list of files to copy
- Replace long FileInstall calls to a simple CopyLangFiles()
- New lang files doesnt need to be added to the script

### CODE REVIEW

**Comment by micwoj92** [comment]
@PierreGrillet I think there's something wrong, because previous workflow was taking almost 90 minutes
https://github.com/rcmaehl/WhyNotWin11/pull/366/checks?check_run_id=2978701574
So I cancelled it and here is new one, if this still takes this long then I can't accept it.
https://github.com/rcmaehl/WhyNotWin11/pull/366/checks?check_run_id=2978968284

**Comment by PierreGrillet** [comment]
Yes working on it

**Comment by PierreGrillet** [comment]
Looks like I haven't documented myself enough on AutoIt framework and the FileInstall function :
https://www.autoitscript.com/autoit3/docs/functions/FileInstall.htm
> The source file must be specified using a string literal and **can not** be a variable, a macro, a calculation nor function call. The file must be able to be found during compiling, however variables, calculations and function calls do not get resolved until the script itself is running, long after compiling, making them unsuitable to define the source file.

**Comment by PierreGrillet** [comment]
Unfortunatly, this i a limitation from AutoIt and the use of a portable exe. I've bring back the FileInstall calls but inside a function to be only be written once in the script. 
Done the same with processors support files, just in case :eyes:

**Comment by mlipok** [comment]
This is limitation from AutoIt but not related to portable version.
Just check documentation for [FileInstall()](https://www.autoitscript.com/autoit3/docs/functions/FileInstall.htm) and you will see:
`The source file must be specified using a string literal and can **not** be a variable, a macro, a calculation nor function call. `

**Comment by PierreGrillet** [comment]
I meant that it works for script version (as I first tested it), but it is not able to compile, and stuck the GitHub checks.

**Review by rcmaehl — APPROVED** [review]

**Pull request merged**
