### PR TITLE
update Discord and GitHub Logo

### PR DESCRIPTION
**Pull request by WilloIzCitron**
Status:

- [x] Tested
- [X] Converted

### CODE REVIEW

**Comment by micwoj92** [comment]
Old icons have higher resolution, just pointing out.

**Comment by WilloIzCitron** [comment]
yes but outdated

**Comment by krystian3w** [comment]
Maybe try convert SVG logo to ICO with upscale to 512x512px.

**Comment by WilloIzCitron** [comment]
ok i do it

**Review by rcmaehl — APPROVED** [review]

**Pull request merged**
