### PR TITLE
spelling correction

### PR DESCRIPTION
**Pull request by keunyop**
spelling correction

### CODE REVIEW

**Comment by micwoj92** [comment]
@level120, @krazyeom, @JeonDohyeon, @papercore-dev, @rophin

**Review by micwoj92 — CHANGES_REQUESTED** [review]
Please add yourself to translators and bump the file version.

**Comment by keunyop** [comment]
> Please add yourself to translators and bump the file version.

Done!

**Review by JeonDohyeon — APPROVED** [review]
I'm approving this changes; and someone has put our nick to metadata and bumped the version

**Review by level120 — APPROVED** [review]
LGTM!

**Pull request merged**
