### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Fix typo: publically -> publicly

### CODE REVIEW

**Comment by micwoj92** [comment]
This last one, right? :fearful:

**Comment by Oleg-Chashko** [comment]
> This last one, right? 😨

I'm tired myself, I have no idea where they come from. You have to be patient, sooner or later they will be over. ;)

**Comment by micwoj92** [comment]
They come from old translation prs that haven't been updated to new template. But I am checking new ones for this mistake. Same with the language codes, couple days ago I was just accepting both, but now only hex, so it is organized better.

**Comment by Oleg-Chashko** [comment]
> They come from old translation prs that haven't been updated to new template. But I am checking new ones for this mistake. Same with the language codes, couple days ago I was just accepting both, but now only hex, so it is organized better.

I got it, thanks for the clarification.

**Pull request merged**
