### PR TITLE
CI improvements

### PR DESCRIPTION
**Pull request by Margen67**
Add pull_request and workflow_dispatch.
Formatting.
Remove unneeded names from checkout and upload-artifact.
Add cache.
Replace Invoke-WebRequest with curl.
Use Start-Process -Wait instead of Start-Sleep hack: #21

### CODE REVIEW

**Comment by micwoj92** [comment]
Thanks for contribution.  I have couple questions first:

What do you mean by " Remove unneeded names from checkout and upload-artifact."?
What are the benefits of using  curl over Invoke-WebRequest?

**Comment by Margen67** [comment]
> 
> 
> Thanks for contribution. I have couple questions first:
> 
> What do you mean by " Remove unneeded names from checkout and upload-artifact."?

The names are almost the same as the actions so they're redundant.

> What are the benefits of using curl over Invoke-WebRequest?

Not having to specify the filename.

**Comment by micwoj92** [comment]
Last question: 
Autoit currently doesn't version downloads, is it possible to let's say purge cache each (x amount of time) to make sure that latest version of tools is using?

Then if you resolve conflicts (checksum output was changed) I can merge this.

**Comment by Margen67** [comment]
> 
> 
> Last question:
> Autoit currently doesn't version downloads, is it possible to let's say purge cache each (x amount of time) to make sure that latest version of tools is being used?
> 
> Then if you resolve conflicts (checksum output was changed) I can merge this.

As far as I know the only way of purging the cache is changing the key.

**Comment by micwoj92** [comment]
Ah, autoit doesn't have that many release anyway, so I think that it is fine to manage that manually.

**Comment by micwoj92** [comment]
Thank you for your contribution!

**Comment by micwoj92** [comment]
hmm, it complains about autoit wrapper missing, even on your repo
https://github.com/Margen67/WhyNotWin11/runs/2937413633?check_suite_focus=true#step:6:17

**Comment by micwoj92** [comment]
I don't think it is critical issue, but if it can't be resolved then I will have to delete cache step which I suspect is the issue (but I might be wrong)

**Pull request merged**
