### PR TITLE
Update 0405.lang

### PR DESCRIPTION
**Pull request by Qazy147**
Translation "Check for Updates" truncated to fit given space. Added "Descriptions".

### CODE REVIEW

**Comment by micwoj92** [comment]
@Sap1k do you agree with these changes/additions?

**Comment by Sap1k** [comment]
- I do agree with @Qazy147 's translation, however, I have a few gripes with the original strings.
- I think the whole higher-end laptop thing is misleading, since nowadays it tends to be higher-end stuff that isn't repairable/upgradable. The same applies for replaceable CPUs in laptops, since it is possible in some models.
- Also it's worth nothing that you won't get a boot in UEFI mode without converting your drive to GPT first, and I think it's worth noting.
- If you'd wish, you could also note that a GPU in a laptop isn't replacable but it is on desktops, since you mentioned it in all other strings related to components.
- Another thing worth noting is that _all_ Intel CPUs from Skylake up have a TPM on the firmware level, if it doesn't it's a matter of replacing the motherboard, not the CPU.

**Comment by rcmaehl** [comment]
@Sap1k Good points. I'll see about adjusting those.

**Comment by Oleg-Chashko** [comment]
> * I do agree with @Qazy147 's translation, however, I have a few gripes with the original strings.
> * I think the whole higher-end laptop thing is misleading, since nowadays it tends to be higher-end stuff that isn't repairable/upgradable. The same applies for replaceable CPUs in laptops, since it is possible in some models.
> * Also it's worth nothing that you won't get a boot in UEFI mode without converting your drive to GPT first, and I think it's worth noting.
> * If you'd wish, you could also note that a GPU in a laptop isn't replacable but it is on desktops, since you mentioned it in all other strings related to components.
> * Another thing worth noting is that _all_ Intel CPUs from Skylake up have a TPM on the firmware level, if it doesn't it's a matter of replacing the motherboard, not the CPU.

@Sap1k 

Hi, I liked your suggestions, if you have a desire please join the discussion: Improving the user interface #271

**Comment by micwoj92** [comment]
>     * I do agree with @Qazy147 's translation, however, I have a few gripes with the original strings.

I will merge this then, feel free to improve later when original strings get updated.

**Pull request merged**
