### PR TITLE
delete checksum file if empty

### PR DESCRIPTION
**Pull request by micwoj92**
This is to address issue where the build fails, but CI doesn't because the .sha256 file exists (although empty)

I've found it online, tested and seems to work, but marking as draft, so maybe some powershell expert will come and help with better solution. Thanks.

### CODE REVIEW

**Comment by htcfreek** [comment]
You can use: `Get-Filehash -Path ... -Algorithm Sha256 | Out-File -Filepath ... -NoNewLine -Force`

**Comment by htcfreek** [comment]
> You can use: `Get-Filehash -Path ... -Algorithm Sha256 | Out-File -Filepath ... -NoNewLine -Force`

The parameters can be a bit different. Not sure if I have it correct in mind.

**Comment by micwoj92** [comment]
> You can use: `Get-Filehash -Path ... -Algorithm Sha256 | Out-File -Filepath ... -NoNewLine -Force`

Does it format the .sha file in the same way as current one is formatted? (look in release for that)

**Comment by micwoj92** [comment]
Powershell was used previously for that, but it was changed to sha256sum tool because of formatting. I think would be better to either 1. make that sha fail if doesnt find files  2. delete file if empty

**Comment by htcfreek** [comment]
You can replace 7zip by `Compress-Archive`.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-5.1

**Comment by micwoj92** [comment]
> You can replace 7zip by `Compress-Archive`.
> 
> https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/compress-archive?view=powershell-5.1

7zip is used later and its output isnt used in prereleases (only in release)

**Comment by htcfreek** [comment]
> Powershell was used previously for that, but it was changed to sha256sum tool because of formatting. I think would be better to either 1. make that sha fail if doesnt find files  2. delete file if empty

What formatting problem? The table?

**Comment by micwoj92** [comment]
> > Powershell was used previously for that, but it was changed to sha256sum tool because of formatting. I think would be better to either 1. make that sha fail if doesnt find files  2. delete file if empty
> 
> What formatting problem? The table?

The file NEEDS to look like this
```
4505a6ed4a5f8a7401d17f76ee8ba73340de5e2905fee2c6c8551d0852d29e9c *WhyNotWin11.exe
eb0f517d97bb1d4cbdab73de9a97ecd0f6e939145b22a37f6b94dd1513d65c34 *WhyNotWin11_x86.exe
```
Does that Powershell output do that?

**Comment by htcfreek** [comment]
you could use this without deleting:

```
checksum ... | out-file -path ... -force
checksum ... | out-file -path ... -append
```

**Comment by htcfreek** [comment]
> > > Powershell was used previously for that, but it was changed to sha256sum tool because of formatting. I think would be better to either 1. make that sha fail if doesnt find files  2. delete file if empty
> > 
> > What formatting problem? The table?
> 
> The file NEEDS to look like this
> ```
> 4505a6ed4a5f8a7401d17f76ee8ba73340de5e2905fee2c6c8551d0852d29e9c *WhyNotWin11.exe
> eb0f517d97bb1d4cbdab73de9a97ecd0f6e939145b22a37f6b94dd1513d65c34 *WhyNotWin11_x86.exe
> ```
> Does that Powershell output do that?

If we can run a script I wrote it last weekend for my own privat repo 😂

**Comment by micwoj92** [comment]
Thanks, I will check that link and your solutions later(Don't have any physical windows computers)

**Comment by micwoj92** [comment]
> If we can run a script I wrote it last weekend for my own privat repo joy

What do you mean? You can technically run any script on github virtual machines. You can for example make pr here and it will run + check for you, with produced files and all that.

**Pull request closed without merging**
