### PR TITLE
Syntax correction

### PR DESCRIPTION
**Pull request by vincent64**
Just a small syntax correction in the french translation.

### CODE REVIEW

**Comment by clinche** [comment]
Applied in #226

**Comment by micwoj92** [comment]
Actually there are 2 French language files. Which one should be kept?
tag @PierreGrillet @villisek

**Comment by PierreGrillet** [comment]
> Actually there are 2 French language files. Which one should be kept?
> tag @PierreGrillet @villisek
I deleted the 1036.lang file in my pull request #226
This typo was also fixed.

**Comment by micwoj92** [comment]
Ok thank you, closing this one then.

**Pull request closed without merging**
