### PR TITLE
EL-GR Translation: Update

### PR DESCRIPTION
**Pull request by Mant08**
**Changelog:**

1. Added new translations.
2. Fixed spelling/gramatical mistakes.
3. Better wording of the translations.
4. Formed the translations, in the same order just as the latest 0000.lang file. (At the time of writing)
5. Adapted the text sizes for a better experience / apearance.
6. Ghanged the Version Number to 2.4.3.2

### CODE REVIEW

**Comment by micwoj92** [comment]
@konmaz, @GalaxyGamingBoy looks good?

**Comment by konmaz** [comment]
Looks good

**Comment by GalaxyGamingBoy** [comment]
Yep!

**Comment by micwoj92** [comment]
Thanks for checking

**Pull request merged**
