### PR TITLE
Merge branch 'main' of https://github.com/rcmaehl/WhyNotWin11

### PR DESCRIPTION
**Pull request by Oleg-Chashko**

### CODE REVIEW

**Comment by micwoj92** [comment]
@Agc0de6 do you agree with changes?

**Comment by Agc0de6** [comment]
@micwoj92 yeah

**Comment by Oleg-Chashko** [comment]
It is necessary to check that all the text corresponds to the length of the string.

**Comment by Oleg-Chashko** [comment]
Typo: publically -> publicly

**Comment by micwoj92** [comment]
Yes, I know, but because you changed that, now this PR will have conflicts most of the time that Robert pushes something to repo. Otherwise I could have merged it already.

**Review by rcmaehl — APPROVED** [review]

**Pull request merged**
