### PR TITLE
EL-GR Corrections

### PR DESCRIPTION
**Pull request by Mant08**
I have done some Spelling and Gramatical corrections to the file.
Also i had fixed the long texts.
You can say is done!

### CODE REVIEW

**Comment by micwoj92** [comment]
Could you please fix this encoding issue? Should be fixed if you open in GitHub text editor rather than uploading file manually.

image

**Comment by Mant08** [comment]
OK, i am up on it

**Comment by Mant08** [comment]
I have re-uploaded the file in UTF-8

**Comment by micwoj92** [comment]
Thank you!

**Pull request merged**
