### PR TITLE
Spanish Translations

### PR DESCRIPTION
**Pull request by JeffersonRussell**
Spanish translations for the following countries:
Hex

### CODE REVIEW

**Comment by rmcpantoja** [comment]
I think there are already many other translations in Spanish. We should agree on something, because I also made a collaboration of this.

**Comment by micwoj92** [comment]
1. Do you think that there is need for all of these Spanish versions?

2. Could you please resolve conflicts with file `Langs/0C0A.lang`?

**Comment by rmcpantoja** [comment]
I consider that it is necessary, since Spanish, as well as English, has many variants of countries, therefore the new method to translate messages is from @MUILang, which means that everything is translated with the language of your country installed in the system. But, we will have to coordinate to update these translations, right?

**Comment by JeffersonRussell** [comment]
> 1. Do you think that there is need for all of these Spanish versions?
> 2. Could you please resolve conflicts with file `Langs/0C0A.lang`?

1. All versions of Spanish are necessary for the language translation to work in all these countries.
2. OK.

**Comment by micwoj92** [comment]
@rmcpantoja could you check if these translations are good and/or comment suggestions? Once you are done I will simply check requirements just to be 100% sure everything is corrent and then merge, will take a bit longer than normal due to size. Thanks for understanding.

**Comment by micwoj92** [comment]
> > 1. Do you think that there is need for all of these Spanish versions?
> > 2. Could you please resolve conflicts with file `Langs/0C0A.lang`?
> 
>     1. All versions of Spanish are necessary for the language translation to work in all these countries.
> 
>     2. OK.

1. I meant more like, are these used by people? For example there might be let's say Spanish United States, but it is almost not used by many people and they use Spanish Spain (for example)

2. Thanks

**Comment by JeffersonRussell** [comment]
> 1. I meant more like, are these used by people? For example there might be let's say Spanish United States, but it is almost not used by many people and they use Spanish Spain.

All are used

**Comment by micwoj92** [comment]
Thanks for translations, please update if you find something wrong!

**Comment by rmcpantoja** [comment]
> @rmcpantoja could you check if these translations are good and/or comment suggestions? Once you are done I will simply check requirements just to be 100% sure everything is corrent and then merge, will take a bit longer than normal due to size. Thanks for understanding.

Well, the translations are fine, only that there are some terms that I think do not match much. They will excuse me, but I will make a language change here:
Unable to Check for Updates=Incapaz de Comprobar las Actualizaciones
El término "incapaz", por ejemplo, y a mi punto de vista, no coincide porque suele ser interpretado de otras formas, en su lugar podría ser "imposible buscar actualizaciones", y lo mismo en esta línea:
Unable to load release data.=Incapaz de Cargar Datos de la Versión
En su lugar, sugeriría mejor "No se han podido cargar los datos de la versión"
Because of what has been said, this terminology can sometimes generate misinterpretations of what is meant.
In fact, I have my translation that I had done just on June 27 when multilanguage support was being implemented, I could share it just in case.
De hecho, tengo mi traducción que había hecho justo el 27 de junio cuando se estaba implementando el soporte multi-idioma, lo podría compartir por si las dudas y para así ir puliendo las traducciones...

**Pull request merged**
