### PR TITLE
Create license file

### PR DESCRIPTION
**Pull request by micwoj92**
Based on the fact that your other tools are also LGPL.

### CODE REVIEW

**Comment by bl-ue** [comment]
Does this work with

>This program is free and open source. Feel free to download and modify. Please do not sell exact copies.

Found at the bottom of the readme?

**Comment by namazso** [comment]
no it does not, selling exact copies is permitted by LGPL

**Comment by micwoj92** [comment]
> Does this work with
> 
> > This program is free and open source. Feel free to download and modify. Please do not sell exact copies.
> 
> Found at the bottom of the readme?

I interpret that as author's wish, not as a requirement.

**Comment by micwoj92** [comment]
It does not say "You must not sell exact copies" or something like that.

**Comment by bl-ue** [comment]
Well, we'll see way @rcmaehl thinks. 🤷🏻‍♂️

**Comment by rcmaehl** [comment]
@namazso @bl-ue Not selling exact copies is more of a request than a licensing requirement.

**Pull request merged**
