### PR TITLE
Update 040D.lang (For the new update)

### PR DESCRIPTION
**Pull request by TheWitherStone**
Hi, I saw you have added a description for every spec that check if it meet the requirement.
I would like to get the updated string list to translate it to Hebrew, Thanks

### CODE REVIEW

**Comment by HypeGameMode** [comment]
I opened this Pull request in my other GitHub account, my bad.

**Review by HypeGameMode — APPROVED** [review]

**Comment by micwoj92** [comment]
@dinuto do you approve this change?

**Comment by micwoj92** [comment]
@HypeGameMode original text is in the 0000.lang file.

**Comment by dinuto** [comment]
Yes.

**Pull request merged**
