### PR TITLE
Added the Spanish language and implementing accessibility for users w…

### PR DESCRIPTION
**Pull request by rmcpantoja**
…ith screen readers.

### CODE REVIEW

**Comment by micwoj92** [comment]
Thank you for your contribution. However it is best if only 1 feature is added per ticket, hence closing this. Feel free to reopen as 2 separate pull requests. Thanks.

**Comment by rmcpantoja** [comment]
Hello,
I did not quite understand the reference of one feature per ticket.
Well, I have to say that I am a bit new to GitHub and I use Git For Windows through the CMD. The changed files, the request to my point of view seem fine, but I will take it into account.
Thanks.

**Comment by micwoj92** [comment]
> I did not quite understand the reference of one feature per ticket.

So for example in one pull request you do Spanish translation and in different one you do that accessibility improvement.

> Well, I have to say that I am a bit new to GitHub and I use Git For Windows through the CMD. The changed files, the request to my point of view seem fine, but I will take it into account.

You can use branches, I see you know how to use them.
So on one branch you change only translation
and on second one the accessibility fix.

Thank you for reply!

**Comment by rmcpantoja** [comment]
Thank you very much, and I apologize for the inconvenience. I will re-create the 2 separate requests to better accommodate it.

**Pull request closed without merging**
