### PR TITLE
#AutoIt3Wrapper_Run_Tidy=Y

### PR DESCRIPTION
**Pull request by mlipok**
For easily keep code clean.

### CODE REVIEW

**Comment by mlipok** [comment]
Compilation was stuck... so I close this PR and will try to investigate.

**Comment by micwoj92** [comment]
Now the CI takes 5 minutes and didn't finish yet, unless there is commandline switch to disable that then I can't merge this.

**Comment by micwoj92** [comment]
> Compilation was stuck... so I close this PR and will try to investigate.

Probably needs command line switch to disable when building.

**Comment by mlipok** [comment]
After when I close this PR I do not see the compilation / checking from workflow.
Could I see them some how ?

**Comment by micwoj92** [comment]
You can go to your repo actions page and run it manually, make sure to set branch as patch-1
image

**Comment by BxOxSxS** [comment]
It's also here:
https://github.com/rcmaehl/WhyNotWin11/runs/2993471858

**Comment by mlipok** [comment]
I was able to replicate this issue on my computer, and will report this to Jos

**Comment by micwoj92** [comment]
Thanks for reporting!

W dniu poniedziałek, 5 lipca 2021 Michał Lipok ***@***.***>
napisał(a):
> I was able to replicate this issue on my computer, and will report this
to Jos
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/ZRvobc52vZheC3R9h3T-zGdeE_NYuDZnsUtisvLc1NdaSkLKEhVtxO53v83wxPtQn4X7Qm1tKCeQgi6ZdjISHzrUkwPTslYrQslKqWRENw__A8ujCOJyLdRJyorDTFFEF8PLbUN7KdiS1YFbr-06z1Y07rD7_4pr6JYPFUArrG1NWKk5QuWv_jvaccMDPlg28LBMN84iQi0LBdRre1mrnrVWqZ4E6J-6EbzjwbWpIA=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4SU64AUSCFFSWYSXVDTWIS45A5CNFSM473KQ5G2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQOW5VY.gif>

**Pull request closed without merging**
