### PR TITLE
Add Indonesian translation 0421.lang

### PR DESCRIPTION
**Pull request by SamCool939**

### CODE REVIEW

**Comment by PierreGrillet** [comment]
https://github.com/rcmaehl/WhyNotWin11/issues/360#issuecomment-873408920
> @PriitUring your instructions are wrong, if you see that new PR you can see that it shows 0000.lang as being removed because of that

You have deleted the 0000.lang file, could you bring it back, please ?

**Comment by SamCool939** [comment]
I'm sorry but the 0000.lang is still on its place. So, may someone here has the way to fix this problem?

**Comment by PierreGrillet** [comment]
Are you on the SamCool939:patch-1 branch ?

**Comment by micwoj92** [comment]
Reverted, will review soon.

**Comment by SamCool939** [comment]
Thanks a lot. 😌

**Review by bl-ue — APPROVED** [review]

**Pull request merged**
