### PR TITLE
Russian language update

### PR DESCRIPTION
**Pull request by AHOHNMYC**
Updated according new template.

### CODE REVIEW

**Comment by rcmaehl** [comment]
@Agc0de6
@Oleg-Chashko

This look good to you all?

**Comment by Agc0de6** [comment]
Looks good.

**Comment by Agc0de6** [comment]
> @Agc0de6
> @Oleg-Chashko
> 
> This look good to you all?

Looks good 👍

**Comment by dmitriy1980** [comment]
translation looks good.

**Pull request merged**
