### PR TITLE
Update Japanese

### PR DESCRIPTION
**Pull request by micachi**
Changed some text to something closer to the original.
#489

### CODE REVIEW

**Comment by micwoj92** [comment]
I will wait couple hours for a reply from current translators here on in linked issue
@yuki-gh @goahi @syobon-tech @arakim

**Comment by arakim** [comment]
syobon-tech did translate freely, arigayas did literally.
I think the translations of arigayas are better in the case.

**Comment by yuki-gh** [comment]
I don't care. Either will do.

**Comment by micwoj92** [comment]
> I don't care. Either will do.

If noone else disagrees in couple hours then I will merge it.

**Comment by arigayas** [comment]
@micachi Thank you for issuing the Pull Request.

**Pull request merged**
