### PR TITLE
Au3Check - compability

### PR DESCRIPTION
**Pull request by mlipok**
will add next file please wait before check and commint

### CODE REVIEW

**Comment by mlipok** [comment]
Ready to check and merge

**Review by rcmaehl — APPROVED** [review]

**Comment by micwoj92** [comment]
@mlipok you can mark your pull requests as drafts when they are not ready

**Comment by mlipok** [comment]
How ?

**Comment by micwoj92** [comment]
image
should be here on right side of the screen

**Comment by micwoj92** [comment]
Or when creating pull request you can click here
image

**Pull request merged**
