### PR TITLE
Update French -France translation

### PR DESCRIPTION
**Pull request by adufourcq**
- Add RTL support
- Update TPM description

### CODE REVIEW

**Comment by micwoj92** [comment]
It shows as binary file on GitHub, can't merge that.

**Comment by rcmaehl** [comment]
Here's a preview of the changes. I'll manually make the changes if people approve. 

image

@PierreGrillet @villisek
Unable to ping: Nits77, BSoD38

**Comment by micwoj92** [comment]
@Nits77 @BSoD38

**Comment by rcmaehl** [comment]
> @Nits77 @BSoD38

Why didn't they autocomplete 🤔

**Comment by micwoj92** [comment]
no idea

**Comment by PierreGrillet** [comment]
The file is encoded in `UCS-2 LE BOM`. It should be in UTF-8.
image

**Comment by micwoj92** [comment]
> The file is encoded in `UCS-2 LE BOM`. It should be in UTF-8.
> image

Yeah, that's why it shows as binary, he uploaded file instead of using GitHub editor, it's just the safest option if you are not sure about encoding and/or line endings.

**Comment by PierreGrillet** [comment]
Translation is fine. 👍

**Pull request closed without merging**
