### PR TITLE
Update _GetDiskInfo.au3

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Fixed typo

### CODE REVIEW

**Review by rcmaehl — APPROVED** [review]

**Comment by micwoj92** [comment]
I don't agree on merging this. @htcfreek was working on updating this
component to latest (1.4.1) version, this would fix that because
@Oleg-Chashko made same pull request on upstream repo.

W dniu środa, 7 lipca 2021 Robert C. Maehl ***@***.***>
napisał(a):
> Merged #425 into main.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/41KXC8R-Cdx67mll3tcUvHvyNCVg2o66U83_a3lnjnh0WUa_v2bw34wLSui_ppKOx6Q0xZh3-2U1v1VQE1sjbyFFr2mDt0EvIl7S4yVJd21UOg087rUhr4Z9O9ZP4k8v3uE4kIlD5MOYJ2QLAT7DCdqDfCF8-GHnzKuODP1FGD0_8wYHrTBax9XmNhIpquNSJ4CPfhXXZylCTZVGtrdOJqFx_FcUeBUmGqmt4_A9PbzeU0EgyQEuGMflBs5tLTQPOs8CU_0=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4TYLMCOSFHX6KBSFTLTWRP6JA5CNFSM476Y5AJKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAJJMZILI.gif>

**Comment by rcmaehl** [comment]
> I don't agree on merging this. @htcfreek was working on updating this component to latest (1.4.1) version, this would fix that because @Oleg-Chashko made same pull request on upstream repo. W dniu środa, 7 lipca 2021 Robert C. Maehl ***@***.***> napisał(a):
> Merged #425 into main. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.<
> https://ci3.googleusercontent.com/proxy/41KXC8R-Cdx67mll3tcUvHvyNCVg2o66U83_a3lnjnh0WUa_v2bw34wLSui_ppKOx6Q0xZh3-2U1v1VQE1sjbyFFr2mDt0EvIl7S4yVJd21UOg087rUhr4Z9O9ZP4k8v3uE4kIlD5MOYJ2QLAT7DCdqDfCF8-GHnzKuODP1FGD0_8wYHrTBax9XmNhIpquNSJ4CPfhXXZylCTZVGtrdOJqFx_FcUeBUmGqmt4_A9PbzeU0EgyQEuGMflBs5tLTQPOs8CU_0=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4TYLMCOSFHX6KBSFTLTWRP6JA5CNFSM476Y5AJKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAJJMZILI.gif>

It's a typo fix. If it regresses we'll just fix it again. Shouldn't cause any conflicts... hopefully

**Comment by micwoj92** [comment]
I also hate replying by email...

W dniu środa, 7 lipca 2021 Robert C. Maehl ***@***.***>
napisał(a):
> I don't agree on merging this. @htcfreek was working on updating this
component to latest (1.4.1) version, this would fix that because
@Oleg-Chashko made same pull request on upstream repo. W dniu środa, 7
lipca 2021 Robert C. Maehl @.***> napisał(a):
> Merged #425 into main. — You are receiving this because you are
subscribed to this thread. Reply to this email directly, view it on GitHub,
or unsubscribe.<
>
https://ci3.googleusercontent.com/proxy/41KXC8R-Cdx67mll3tcUvHvyNCVg2o66U83_a3lnjnh0WUa_v2bw34wLSui_ppKOx6Q0xZh3-2U1v1VQE1sjbyFFr2mDt0EvIl7S4yVJd21UOg087rUhr4Z9O9ZP4k8v3uE4kIlD5MOYJ2QLAT7DCdqDfCF8-GHnzKuODP1FGD0_8wYHrTBax9XmNhIpquNSJ4CPfhXXZylCTZVGtrdOJqFx_FcUeBUmGqmt4_A9PbzeU0EgyQEuGMflBs5tLTQPOs8CU_0=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4TYLMCOSFHX6KBSFTLTWRP6JA5CNFSM476Y5AJKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGPAAAAAAJJMZILI.gif
>
>
> It's a typo fix. If it regresses we'll just fix it again. Shouldn't cause
any conflicts... hopefully
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/-JEqfqEYj9kPEKunwrDypXKReGEPFCJqXvC3oLl9kCykMwo8E4orn-qhpNtp1lyS_6EFsmfQK-4OPB42JMiniXM5quTPGmB8bUmWJkYea2bRF908Bs4dRF005qwauAkGULGsPX3HgrwnaUZWE3QonAVGmJLrpxX9Deo74eIIdtV4ljnmmDhCFC26HUq1O2Hg0tFn88-YnGaEgHtA-n-BCUKXCblL2Qe1eTVSPRLCnQ=s0-d-e1-ft#https://github.com/notifications/beacon/AK3YG4WQV6QNEPLXH4ZCJP3TWRURTA5CNFSM476Y5AJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGQY6E3Y.gif>

**Comment by htcfreek** [comment]
can we please use the original file name here like on resource ex. it's ban external "udf".

**Pull request merged**
