### PR TITLE
Update WhyNotWin11.au3

### PR DESCRIPTION
**Pull request by Qazy147**
Line 641 overwrites any previous settings.

### CODE REVIEW

**Comment by mlipok** [comment]
please use meaningful descriptions in the title indicating what is being changed in a way that describes the nature of the problem.

**Comment by micwoj92** [comment]
@Qazy147 could you fetch upstream changes so it builds?

**Comment by Qazy147** [comment]
Sorry, i don't know how to describe it better. Line 638
```
GUICtrlSetData($hCheck[6][2], _Translate($iMUI, "GPT Not Detected") & @CRLF & "0 " & _Translate($iMUI, "Drive(s) Meet Requirements"))
```
 is pointless because it's overwritten by line 642
```
GUICtrlSetData($hCheck[6][2], _Translate($iMUI, "GPT Detected") & @CRLF & $aDisks[1] & "/" & $aDisks[0] & " " & _Translate($iMUI, "Drive(s) Meet Requirements"))
```
So This line 642 should by replaced with 3 separate lines each for every part of condition.

**Comment by mlipok** [comment]
You do this wrong way.

Go to your's branch
https://github.com/Qazy147/WhyNotWin11/tree/patch-7

Use this feature:
image

**Review by rcmaehl — APPROVED** [review]

**Pull request merged**
