### PR TITLE
incorporates latest English changes

### PR DESCRIPTION
**Pull request by yuki-gh**

### CODE REVIEW

**Comment by micwoj92** [comment]
Will convert to draft for now, waiting for the other PR to be merged first.

**Comment by micwoj92** [comment]
@yuki-gh could you fix conflicts?

**Comment by yuki-gh** [comment]
I took more straightforward translation as per #489 .

**Comment by micwoj92** [comment]
I don't know if you did this by accident or on purpose , but descriptions are in English. It should be translated, otherwise it makes no sense to include these changes.

**Pull request closed without merging**
