### PR TITLE
Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@rcmaehl 

Please check and update. Thanks.

### CODE REVIEW

**Comment by micwoj92** [comment]
It's not up to Robert, you should ping previous translators.

**Comment by bovirus** [comment]
@rcmaehl 

Why that?
The translation is more or less the same.
Jist reveiw some strings.
Added some new string not included in original file.
I left as starting the original translator names.
Then waht's the problem?
If they want change it agian can do that with anew PR.

Please reming to add "Architecture" to the list of changes.

**Comment by micwoj92** [comment]
I propose you read contribution and translation guidelines.

**Comment by bovirus** [comment]
@micwoj92 

Could you to explain why did you close the PR?

Could you please you rad carefully the guideline

https://github.com/rcmaehl/WhyNotWin11/blob/main/Langs/0000-translating-guidelines.md

**Existing Translations**
Previous translators will be notified and will have 24h to reply. 
After all parties agree, translation will be updated.

I disagree about many curremt strings about current Italian translation because seems translated by an italian translator but by an automatic transaltor system and don't reflect the look and feel of Italian language.

There is the same terms translated in different way like "identificato" o "rilevato" 
Wrong use of uppercase (In italian grammar only first word of a string is in uppercase except own names).
String without a sense in italian and in a software environment Like "Hai la versione più recente!" 
String withour sense about the use of position for the adjective like "Un aggiornamento è disponibile, vuoi scaricarlo?"

I can continue a lot!

**Comment by micwoj92** [comment]
> @micwoj92
> @micwoj92

No need to ping (twice??)me, I see all messages on this repo

> **_As professional translator I disagree about some current strings of Italian translation because don't reflect the look and feel of Italian language._**

I don't know who you (nor previous translators) are.

> There is the same terms translated in different way like "identificato" o "rilevato"
> Wrong use of uppercase (In italian grammar only first word of a string is in uppercase except own names).
> String without a sense in italian and for software environment like "Hai la versione più recente!"
> String withour sense about the use of position for the adjective like "Un aggiornamento è disponibile, vuoi scaricarlo?"
> 
> These are only some examples why current Italian translation for me is not compatible with italian grammar and terminoligy for software environment.
> 
> **The current translation for some strings don't reflect the sense of Italian language.**

I don't speak Italian, so I rely on machine translation and on previous translators to check these pull requests and I really don't care when you said that you "propose to apply this pr". You should just follow the guidelines: Open pull request, ping previous translators to discuss/seek approval and then we can merge.

**Comment by bovirus** [comment]
There is no sense to spent again my spare time without a result.
I already posted a professional translation to update and fix error of previous tarnslations  that are clear for who know well italian language.
The current translator didn't check their job, didn't update it and the currrnt translation contains several errors about italian language as grammar and terminology for software environment,.
I push my PR,
Result, No one, Same errors like before. Just a small refresh.
Thanks. But probably your translator are not habit to translate Italian string for sofwtare environment.
I prefer to spent my spare time is I see some result.
Otherwise I prefer spent time in other project.
As I said the curernt translation contains errors that is not good for my language.

**Pull request closed without merging**
