### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Removed tab and added Whitespaces

### CODE REVIEW

**Comment by micwoj92** [comment]
Contributing guidelines
"Tabs, not spaces, with tab width set to 4"

**Comment by micwoj92** [comment]
I don't know that much about best AutoIt practices, @mlipok @rcmaehl could you share your expertise on this?

**Comment by Oleg-Chashko** [comment]
> Contributing guidelines
> "Tabs, not spaces, with tab width set to 4"

This is how I can see, I see all these tabs and Whitespaces:
Screen Shot 2021-07-05 at 22 40 47

**Comment by mlipok** [comment]
I just use Tidy.exe (with almost default settings) as a part of SciTE4AutoIt.

**Comment by Oleg-Chashko** [comment]
I see: grammatical errors, in different languages, etc.
Visual Studio Code:
Screen Shot 2021-07-05 at 22 51 53

**Comment by micwoj92** [comment]
I additionally ran tidy on this, will merge now. But I wouldn't really call this "Fixed typos", maybe "Fixed indentation"?

**Comment by Oleg-Chashko** [comment]
> I additionally ran tidy on this, will merge now. But I wouldn't really call this "Fixed typos", maybe "Fixed indentation"?

Screen Shot 2021-07-05 at 23 01 05

**Comment by micwoj92** [comment]
I know what tab and space is.

**Comment by Oleg-Chashko** [comment]
> I additionally ran tidy on this, will merge now. But I wouldn't really call this "Fixed typos", maybe "Fixed indentation"?

Fixed indentation.

**Comment by Oleg-Chashko** [comment]
> I know what tab and space is.

I know you know this, I just showed you how I see it in the program "Visual Studio Code".

**Pull request merged**
