### PR TITLE
Update russian language

### PR DESCRIPTION
**Pull request by DockedFerret800**
- Error correction

### CODE REVIEW

**Comment by micwoj92** [comment]
@Agc0de6 @Oleg-Chashko Do you agree with these changes?

**Comment by Agc0de6** [comment]
@micwoj92 no

**Comment by Oleg-Chashko** [comment]
1. Error correction -> There is not a single error in the localization.
2. @DockedFerret800: You have a problem with the gender of words in a sentence.

**Comment by DockedFerret800** [comment]
🤦‍♂️

**Comment by micwoj92** [comment]
> man_facepalming

You should have read translation guidelines.

**Pull request closed without merging**
