### PR TITLE
Add download link to README

### PR DESCRIPTION
**Pull request by bl-ue**
This app has a high download rate, estimating at about 20-40 downloads per minute.  It currently has about 1.6k downloads.
Providing a link directly on the README will make it much easier to download, and it still increments the download count.

### CODE REVIEW

**Comment by namazso** [comment]
i'd recommend using /releases/latest/download instead of hardcoding version numbers

**Comment by bl-ue** [comment]
I tried https://github.com/rcmaehl/WhyNotWin11/releases/download/latest/WhyNotWin11.exe but it didn't work 🤔

**Comment by namazso** [comment]
because it's https://github.com/rcmaehl/WhyNotWin11/releases/latest/download/WhyNotWin11.exe

**Comment by bl-ue** [comment]
Aha! Clever! I'll use that ASAP.

**Comment by bl-ue** [comment]
Done ☝🏻

**Comment by micwoj92** [comment]
I don't think it should link directly do .exe download, look for example at NCC's readme
https://github.com/rcmaehl/NotCPUCores/blob/master/README.md

**Comment by bl-ue** [comment]
Good point, _if_ there are more assets. The NCC releases distribute 3 binaries — (so far) this project only does one, so you're only going to download what this link already points to ;)

**Comment by rcmaehl** [comment]
LGTM!

**Pull request merged**
