### PR TITLE
Fixing strange Static usage > Const

### PR DESCRIPTION
**Pull request by mlipok**
I do not understand why somebody use Static in this case, IMHO it should be declared as Const .

### CODE REVIEW

**Comment by rcmaehl** [comment]
I need to improve the existing code. This Static was going to use this to keep whatever language the GUI was changed to by calling Main() within Main(). I'm unsure if this is good coding practice, but unlike Python it doesn't seem to cause any sort of memory leak.

**Comment by micwoj92** [comment]
you do not need to do that every commit

**Comment by mlipok** [comment]
This was not related to this PR.
I was checking something on my branch.

**Comment by mlipok** [comment]
> This Static was going to use this to keep whatever language the GUI was changed to by calling Main() within Main().

What is your plan for this ?

**Pull request closed without merging**
