### PR TITLE
Chinese(Simplified) translation

### PR DESCRIPTION
**Pull request by BluesDawn576**

### CODE REVIEW

**Comment by walterlv** [comment]
I think this translation is better than the other one #105. The texts on the UI seem more like on a Chinese native software.

‎我认为这版翻译比另一个好点。界面上的文字看起来更像是一款国产软件。‎

**Comment by micwoj92** [comment]
@walterlv so leave this open and close #105 ? Also, could you take a look at  #126 to see if anything there is better? Thank you.

**Comment by micwoj92** [comment]
Merging this now, feel free to submit any patches later!

**Comment by BluesDawn576** [comment]
thanks

**Pull request merged**
