### PR TITLE
Improve spanish translation

### PR DESCRIPTION
**Pull request by CodartLabs**

### CODE REVIEW

**Comment by micwoj92** [comment]
@Konata400 @JeffersonRussell

Do you agree with these changes?

**Comment by Konata400** [comment]
Yes

**Comment by rmcpantoja** [comment]
The accessibility part is missing, luckily it is not much.
I'm going to see if these days I do a pull request updating the translation template 0000 and a user manual of the keybindings and upload it to Github. I can help with the translation too, as I was one of the first to do it.

**Comment by JeffersonRussell** [comment]
> @Konata400 @JeffersonRussell
> 
> Do you agree with these changes?

No, the new translation is too long and there is not enough space.

**Comment by rcmaehl** [comment]
Confirmed @JeffersonRussell's statement

**Pull request closed without merging**
