### PR TITLE
*.lang files # support for Cores/Threads

### PR DESCRIPTION
**Pull request by mlipok**

### CODE REVIEW

**Comment by htcfreek** [comment]
Can we create a general feature that allows us to do replacement?

Idea:
Translation has an input param for an array. For each element in array the corresponding value in text will be replaced. This mean for array[0] the value `#0` or `%0`, for array[1] the value `#1` or `%1`, ... will be replaced.

**Comment by mlipok** [comment]
I think that %0 will be better as this can be used with StringFormat() 
But I'm not sure if StringFormat() will hit other/new issues with some other characters used in other *.lang files, I mean characters which could be specific for some Languages.

**Comment by mlipok** [comment]
For example in 040D.lang I found 
`Translator= HypeGameMode (Random The Score Fan#0001)`
but as so far `%` is used only in `0000-REFERENCE-GUIDE.txt`

So it looks like StringFormat() will be better solution.

**Comment by htcfreek** [comment]
> For example in 040D.lang I found 
> `Translator= HypeGameMode (Random The Score Fan#0001)`
> but as so far `%` is used only in `0000-REFERENCE-GUIDE.txt`
> 
> So it looks like StringFormat() will be better solution than using StringReplace() for `#` char.
> 
> But for now it will be a problem to determine if any replacement was taken with StringFormat() in the same way as with StringReplace() via `@extended` marcro.
> 
> Any sugestions ?
> 

I think we should definitely not switch to `StringFormat()` because of the reason your described.

But I see no reason to not use `StringReplace()`.

**Comment by micwoj92** [comment]
> For example in 040D.lang I found
> `Translator= HypeGameMode (Random The Score Fan#0001)`
> but as so far `%` is used only in `0000-REFERENCE-GUIDE.txt`

No longer the case
https://github.com/rcmaehl/WhyNotWin11/blob/4ba87e2fd5092e4566b71b1473b4a38a76b359d9/Langs/040D.lang#L3

**Comment by rcmaehl** [comment]
Looks good, was needing to implement something like this. If there's elsewhere that this can be applied put a PR so it can be merged

**Comment by mlipok** [comment]
> If there's elsewhere that this can be applied put a PR so it can be merged

?

**Comment by micwoj92** [comment]
I think he meant other parts of gui where the same change could be made.

**Pull request merged**
