### PR TITLE
Update GPT Results

### PR DESCRIPTION
**Pull request by DanGM96**
I just remade this section using a simpler logic, removed `number/number` because it wasn't that helpful and was different to **Storage Available** results pattern.
It would be a good idea to make `_GetDiskInfo` return only Disks that passed the **Storage Available** 64 GB test, since a GTP disk with less than that would not be compatible, but I was not sure how to get disk size from inside the function.

### CODE REVIEW

**Comment by micwoj92** [comment]
@DanGM96 Could you resolve conflicts with ` WhyNotWin11.au3 `?

**Comment by DanGM96** [comment]
Yes, the way it was working, whenever it identified a GTP disk, it would always end up on old line 564.

On my system it would be "[X] GTP Detected 0/1 Drive(s) Meet Requirements", which was correct but really confusing before @rcmaehl told me it was `bootableGTP/non-bootableGTP` GTP disks. Maybe a better way would be `bootableGTP/all-disks`.

So in my opinion it would be better to pass only if there is one or more GPT disks, then fail the rest. Then I removed the `/number` from the result, but I can add it back if you guys want.

**Comment by micwoj92** [comment]
I don't think we mean the same things, I meant this
image

**Comment by htcfreek** [comment]
@DanGM96 
Your change is only affects ui and not the check itself. Correct?

**Comment by DanGM96** [comment]
> I don't think we mean the same things, I meant this

Oh hehe, as you can see I'm not the best at using github.

> @DanGM96
> Your change is only affects ui and not the check itself. Correct?

Yes, the real check is at the `/includes/` files

**Comment by rcmaehl** [comment]
If not a fan of this code as it seems it passes on any disk having GPT, even if the Windows Disk is not. Granted, this is a shortcoming of the WMI call (#162)

**Comment by DanGM96** [comment]
It's alright, I tried to make it simple and made it too simple. I don't think the change is suitable anymore.
But still the `GUICtrlSetData()` inside `ElseIf $aDisks[0] = 0 Then` is useless as it's replaced right after the `EndIf`.

**Pull request closed without merging**
