### PR TITLE
Update kbc.au3

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Tidy source code

### CODE REVIEW

**Review by rcmaehl — APPROVED** [review]

**Comment by micwoj92** [comment]
What is the change here?

**Comment by Oleg-Chashko** [comment]
Added empty line:
Screen Shot 2021-07-11 at 18 33 43

**Comment by micwoj92** [comment]
But is it something that "tidy" tool from autoit did? I just never saw this change so wondering.

**Comment by Oleg-Chashko** [comment]
> But is it something that "tidy" tool from autoit did? I just never saw this change so wondering.

Visual Studio code with the "Autoit" extension:
Screen Shot 2021-07-11 at 18 53 09

**Pull request merged**
