### PR TITLE
#217 Fix french translation texts are too long

### PR DESCRIPTION
**Pull request by PierreGrillet**
#217 Fix french translation texts are too long

Applied suggestions by [@BSoD38](https://github.com/BSoD38). Added him into translators.

### CODE REVIEW

**Comment by clinche** [comment]
Le fichier devrait être 040C.lang, et non pas 1036.lang ?

**Comment by PierreGrillet** [comment]
True, fixing it

**Comment by PierreGrillet** [comment]
Ready. :+1:

**Comment by PierreGrillet** [comment]
Edited Reference guide as it was not specifying to pick hexadecimal numbers.

**Review by clinche — APPROVED** [review]
all good

**Comment by micwoj92** [comment]
Oh, sorry guys. I have updated and renamed the reference guide Before I saw in this pr (same thing as you did).

If you resolve conflicts, then I will merge. Thanks!

**Comment by PierreGrillet** [comment]
Done 👍

**Pull request merged**
