### PR TITLE
Update 0419.lang

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Update Russian

### CODE REVIEW

**Comment by micwoj92** [comment]
@Agc0de6 Do you approve these changes?

**Comment by Agc0de6** [comment]
@micwoj92 yeah

**Comment by Oleg-Chashko** [comment]
@micwoj92
There is nothing left of the primary localization in this file.

**Comment by micwoj92** [comment]
If you look at the git blame you can see that some strings are still from the original
https://github.com/rcmaehl/WhyNotWin11/blame/main/Langs/0419.lang

**Pull request merged**
