### PR TITLE
Fix syntax error - lack of " after FeatureLevels:12

### PR DESCRIPTION
**Pull request by aman-atg**

### CODE REVIEW

**Comment by mlipok** [comment]
Please change your PR title to:


Fix syntax error - lack of " after FeatureLevels:12

**Comment by mlipok** [comment]
Thanks for changing title.

I was by mistake post the same change here:
https://github.com/rcmaehl/WhyNotWin11/pull/279

Of course I close them

**Comment by micwoj92** [comment]
Sorry, didnt see this

**Comment by micwoj92** [comment]
Need to organize my e-mail :/

**Comment by mlipok** [comment]
no no .
I close my own because it was pulled by my mistake.
Your's PR should stay opened and commited by @rcmaehl

**Comment by micwoj92** [comment]
@mlipok I meant I commited the same change before seeing this pr, check latest commit.

**Comment by micwoj92** [comment]
> no no .
> I close my own because it was pulled by my mistake.
> Your's PR should stay opened and then after accepting should be commited by @rcmaehl
> But for this it should stay opened so @micwoj92 please reopen your PR.

It's not my pr ;p

**Comment by mlipok** [comment]
Oh I just notice that.
Thanks.

But could you next time closing PR add proper LINK as a reference
https://github.com/rcmaehl/WhyNotWin11/commit/59074719ed3cba9752bb0aa70d640aa06d5d8105

**Comment by aman-atg** [comment]
> Sorry, haven't seen this

No problem.

**Comment by micwoj92** [comment]
> But could you next time closing PR add proper LINK as a reference
> [5907471](https://github.com/rcmaehl/WhyNotWin11/commit/59074719ed3cba9752bb0aa70d640aa06d5d8105)

Yeah, will next time. In a bit of hurry right now.

**Pull request closed without merging**
