### PR TITLE
Update _GetDiskInfo.au3

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
Fixed: Envget -> EnvGet

### CODE REVIEW

**Comment by htcfreek** [comment]
Please don't merge! It's never a good idea to change external includes. And a fix for this exists in a newer version of the included function!

**Comment by micwoj92** [comment]
I agree with @htcfreek

**Comment by Oleg-Chashko** [comment]
I'd love to hear what @rcmaehl has to say about this.
Are you guys sure about this? 
In the program code, it says EnvGet everywhere as I fixed it.
Should everything be in the same style or not?

Screen Shot 2021-07-12 at 07 02 35

**Comment by htcfreek** [comment]
The fix for it is in n #488. So it gets fixed hopefully soon.

**Comment by Oleg-Chashko** [comment]
> The fix for it is in n #488. So it gets fixed hopefully soon.

So what are we changing for: EnvGet -> Envget or Envget -> EnvGet?

**Comment by htcfreek** [comment]
@Oleg-Chashko 
You fork is out of date.

**Comment by Oleg-Chashko** [comment]
@htcfreek 
Thanks, Heiko.

**Comment by Oleg-Chashko** [comment]
@rcmaehl, @micwoj92

 Will you open Branch and Merged? 
It would be a good idea to correct this typo?

**Comment by htcfreek** [comment]
> @rcmaehl, @micwoj92
> 
>  Will you open Branch and Merged? 
> It would be a good idea to correct this typo?

Which typo? The `g` or the duplicate file?

Btw.: Both will be fixed with #448.

**Comment by micwoj92** [comment]
> @rcmaehl, @micwoj92
> 
> Will you open Branch and Merged?
> It would be a good idea to correct this typo?

No, for the reasons stated above (#488)
image

**Pull request closed without merging**
