### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by PierreGrillet**
- Adding font size (reduce Large to 14)
- Fix Clipping text
- Translate CPU and OS

### CODE REVIEW

**Comment by micwoj92** [comment]
Could you change all translator names to their GitHub username? And seek approval from at least one? Thanks.

**Comment by PierreGrillet** [comment]
Can I have approval from any french speaker ?
@Nits77, @villisek, @ghost, @vincent64 ?
:pray: :smile:

**Comment by micwoj92** [comment]
"ghost" can be removed, it was someone that deleted their GH account.

**Review by vincent64 — APPROVED** [review]
Sounds good to me!

**Comment by micwoj92** [comment]
thx for update

**Pull request merged**
